
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'kkbox_churn'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'continual'

vars:
    churn_threshold: 30
    todays_date: '2017-04-01'
    train_start: '2016-06-01'
    train_end: '2016-01-01'
    vali_start: '2016-01-01'
    vali_end: '2017-02-01'
    test_start: '2017-02-01'
    test_end: '2017-03-01'


# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  kkbox_churn:
      materialized: view
      +schema: kkbox_churn
      +meta: {
        "continual" : {
          "create_stub": True,
          "create_exposures": True,
          "create_sources": True,
          }
        }
