version: 2

sources:
    - name: churn
      database: kkbox
      description: Source datasets for kkbox churn model
      tags: ['kkbox']
      tables:
        - name: members
        - name: transactions
        - name: user_logs
